Add labels to PRs (61)
kustomize-everything/action-promote pull request #62
Opened 2023-10-20 07:51 UTC by gezapeti

2023-10-20 20:47 UTC, gezapeti commented
I don't thing anything in the failed actions is related to the change. It looks like some access issue.

2023-11-17 18:46 UTC, highb requested changes

2023-11-17 18:46 UTC, highb commented on src/commit-and-pull-request.sh
> +  if [[ "${LABELS}" ]]; then
```suggestion
  if [[ -n "${LABELS}" ]]; then
```

2023-11-17 18:46 UTC, highb commented on src/commit-and-pull-request.sh
> +  if [[ "${LABELS}" ]]; then
Should check for non-null string here with -n.

2023-11-18 01:26 UTC, highb commented
I'll merge this and test it out before releasing, since the github token seems to be unavailable from a fork.

2023-11-18 01:54 UTC, highb commented
Ended up making an additional change over in #62 , so I'll close this PR. I'll be releasing this change as v4.2.0. 🥳 

Thank you for the contribution @gezapeti !

2023-11-18 01:54 UTC, closed without merging